### PR TITLE
Guidelines

### PR DESCRIPTION
**Pull request by riker09**
I've changed the code formatting for a better readability. If you like it please tell me, I can fix the rest of the files.

### CODE REVIEW

**Comment by dracony** [comment]
I like the idea, but I really prefer tabs to spaces. I know formatting is a bit of an issue here, mostly because I use different code editors while I am at home and at work, but I was thinking about running some autoformatter tool. If you could set your editor to save as tabs it would be cool =)

**Comment by riker09** [comment]
Yeah, tabs vs. spaces, one of the oldest battles in programmer history. :)

I've decided to use spaces since they always have the same intendation, but that's really something of a personal choice. I'm using Netbeans 7.3 to apply some general PHP coding guidelines, works pretty well for me.

I've noticed that most files were mixed with tabs and spaces, that's why I decided to act on it in the first place.

**Comment by dracony** [comment]
Well, I'll take it as call to arms for some formatting, I don't have much work for today, so I'll sit down and make everything pretty manually =)
There's still pretty of things that can be done if you want to help though =)) Of the top of my head that would be an image processing module with drivers for gd/imagick/gmagick and implementing __sleep for ORM so that the results can be cached.
I'm going to work on adding UNION and subquery support to the query builder today

**Comment by riker09** [comment]
Okay, I've changed my Netbeans settings to tabs instead of spaces. Hopefully I've merged your latest changes correct. Please have a look!

**Comment by dracony** [comment]
Awesome thanks! I'll take a look a bit later when I get home =)

**Comment by dracony** [comment]
Hm, the merge didn't go well for the PDO driver class, I'll try fixing it

**Comment by dracony** [comment]
Fixed it! the union() method was missing after merge, so it was a quick fix.
Keep in mind that you should run tests with phpunit (it's very simple even if you never used it before) to test if the changes didn't break something =)

**Comment by riker09** [comment]
I'm having trouble getting the unit test to work with phpunit. I've setup a default installation under Ubuntu 12.04. It seems that include paths are wrong in the test files.

```
PHP Warning:  require_once(/../../../../modules/database/classes/database/expression.php): failed to open stream: No such file or directory in /home/user/projects/phpixie/tests/modules/database/database/expressionTest.php on line 3
```

When I change the absolute path to `require_once(dirname(__FILE__).'/../../../../modules[...]'` I can get rid of this error, but then phpunit complaines that the class `Misc` is missing. I'm using the test file `/tests/modules/orm/ormTest.php`

**Comment by dracony** [comment]
This is strange indeed, I should've refactored the includes inside tests some time ago, but I never had any problems with them.
the Misc class is included in the same way in configTest.php
I'll change the includes tomorrow morning so it should work on any setup.
from the top of my head: try 'cd' to the the 'tests' directory before running PHPunit, I suspect PHP takes the path relative to your current folder on Linux.
Tell me if that fixes it =)

**Comment by riker09** [comment]
There's no need to fix the test case files. I've already done that and created another pull request for it. :)

**Pull request merged**
