### PR TITLE
Fixed test cases

### PR DESCRIPTION
**Pull request by riker09**
It looks like the test files were using wrong path values. I tried fixing it by prefixing dirname(**FILE**) whereever necessary. While most tests are completing successfully now I'm still having issues with a missing class `Misc` in some cases. For instance:

```
user@ubuntu:~/projects/phpixie$ phpunit tests/system/requestTest.php 
PHPUnit 3.7.18 by Sebastian Bergmann.

PHP Fatal error:  Class 'Misc' not found in /home/user/projects/phpixie/system/classes/request.php on line 72
```

### CODE REVIEW

**Comment by dracony** [comment]
Hm, the tests run just fine over here =) I assume you have found a solution to the Misc class issue?

**Comment by riker09** [comment]
Sorry, no. I don't have much time besides my daily work. It _should_ be fairly easy to reproduce/fix. I'm assuming that there's some sort of autoloading taking place on your setup. So the test files should include the Misc class as a dependency.

**Comment by dracony** [comment]
Alright, I'll fix it when I get home, I have Arch Linux on my notebook there =)

**Comment by dracony** [comment]
Ok, I think I fixed everything, I refactored th tests to use prefixed path instead of relying on dirname. I don't know if it works on linux yet though, still not home =)

**Comment by riker09** [comment]
Looks like it's working again:

```
user@ubuntu:~/projects/phpixie$ phpunit --bootstrap tests/bootstrap.php tests/
PHPUnit 3.7.18 by Sebastian Bergmann.

...............................................................  63 / 103 ( 61%)
........................................

Time: 9 seconds, Memory: 11.75Mb

OK (103 tests, 251 assertions)
```

**Comment by dracony** [comment]
Awesome!

**Pull request merged**
